# Subscribe to PyShine Youtube channel for the upcoming educational videos
# Lets write the face detection code
import matplotlib.pyplot as plt
import matplotlib.animation as animation
import numpy as np
# Get the Figure
fig = plt.figure()
ax = fig.add_subplot(1,1,1)
# ax.set_facecolor((0,0,0)) # Set the background to black
#
xs = []
ys = []
ax.set_ylim([-1 , +1])
ax.set_xlim([-1, +1])
t = np.linspace(0,2*np.pi,100)
xx = np.cos(t)
yy = np.sin(t)
def animate(i):
    ax.clear()
    # xs = [0]
    # ys = [0]
    # graph_data = open('file.csv','r').read() # Open file.csv generated by Face.py
    # lines = graph_data.split('\n')
    #for line in lines[1:]:
    #    if len(line) > 1: # Skip the first labels line in csv file
    #        x, y = line.split(',')
    x = xx[i]#np.cos(2*np.pi*i)
    y = yy[i]#np.sin(2*np.pi*i)
    #if np.equal([xs[-1],ys[-1]],[x,y]).all():
    xs.append(float(x))
    ys.append(float(y))
    # print(xs,ys)
    # Lets add these lists xs, ys to the plot
    ax.clear()
    ax.plot(xs, ys, color = (0,1,0.25))
    # ax.set_xlabel("Samples")
    # ax.set_ylabel("Frame Rate")
    # ax.set_title("Live Plot of Camera Frame Rate")
    # fig.tight_layout() # To remove outside borders
    ax.yaxis.grid(True)
# Lets call the animation function
ani = animation.FuncAnimation(fig, animate, interval=1)
plt.show()